version: '3'
services:
  postgres:
    image: "postgres:13"
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
  elastic:
    image: ghcr.io/yp-middle-python-24/elasticsearch:8.7.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  etl:
    build: etl
    env_file:
      - ./.env
    depends_on:
      - nginx
      - service
      - elasticsearch
volumes:
  elasticsearch-data:
    driver: local
